	 <div id="rev_slider_3_1_wrapper" class="rev_slider_wrapper fullscreen-container" style="background-color: rgb(233, 233, 233); padding: 0px; height: 631px; max-height: none; overflow: visible;">
	<div id="rev_slider_3_1" class="rev_slider fullscreenbanner revslider-initialised tp-simpleresponsive hovered" style="height: 100%; max-height: none;">
	 <ul style="display: block; overflow: hidden; width: 100%; height: 100%; max-height: none;" class="tp-revslider-mainul">	
<!-- SLIDE  1-->
	<li data-transition="fade" data-slotamount="1" data-masterspeed="1500" data-delay="13000" data-saveperformance="off" class="tp-revslider-slidesli active-revslide" style="width: 100%; height: 100%; overflow: hidden; z-index: 18; visibility: hidden; opacity: 0;">
		<!-- MAIN IMAGE -->
		<div class="slotholder" style="width:100%;height:100%;" data-duration="14000" data-zoomstart="undefined" data-zoomend="undefined" data-rotationstart="undefined" data-rotationend="undefined" data-ease="Linear.easeNone" data-bgpositionend="right center" data-bgposition="left center" data-kenburns="on" data-easeme="Linear.easeNone" data-bgfit="100" data-bgfitend="130" data-owidth="undefined" data-oheight="undefined"><div class="tp-bgimg defaultimg" data-lazyload="undefined" data-bgfit="100" data-bgposition="left center" data-bgrepeat="no-repeat" data-lazydone="undefined" src="http://demo.joomlead.com/arc/images/lead/slides/1.jpg" data-src="http://demo.joomlead.com/arc/images/lead/slides/1.jpg" style="background-color: rgba(0, 0, 0, 0); background-repeat: no-repeat; background-image: url(&quot;http://demo.joomlead.com/arc/images/lead/slides/1.jpg&quot;); background-position: 6.01787% 0%; width: 100%; height: 100%; opacity: 1; visibility: inherit; background-size: 125.037% 122.586%; transform: matrix(1, 0, 0, 1, 0, 0);"></div></div>
		<!-- LAYERS -->

		<!-- LAYER NR. 1 -->
		<div class="tp-caption large_text lft fadeout tp-resizeme start" data-x="center" data-hoffset="0" data-y="center" data-voffset="-140" data-speed="900" data-start="500" data-easing="Power4.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.15" data-endelementdelay="0.1" data-endspeed="1000" data-endeasing="Power1.easeOut" style="z-index: 5; max-width: none; max-height: none; white-space: nowrap; min-height: 0px; min-width: 0px; line-height: 36px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 4px; font-size: 27px; left: 527px; top: 171.3px; visibility: visible; opacity: 0; transform: translate3d(0px, 0px, 0px);">bedroom interior
		</div>

		<!-- LAYER NR. 2 -->
		<div class="tp-caption finewide_large_white lfb fadeout tp-resizeme start" data-x="center" data-hoffset="0" data-y="center" data-voffset="-40" data-speed="1200" data-start="500" data-easing="Power4.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.05" data-endelementdelay="0.1" data-endspeed="300" data-endeasing="Power1.easeOut" style="z-index: 6; max-width: none; max-height: none; white-space: nowrap; min-height: 0px; min-width: 0px; line-height: 54px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 2px; font-size: 65px; left: 386px; top: 252.443px; visibility: visible; opacity: 0; transform: translate3d(0px, 0px, 0px);">Design Awards
		</div>

		<!-- LAYER NR. 3 -->
		<div class="tp-caption sfr fadeout tp-resizeme start" data-x="center" data-hoffset="0" data-y="center" data-voffset="80" data-speed="1300" data-start="510" data-easing="Power4.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.15" data-endelementdelay="0.1" data-endspeed="300" data-endeasing="Power1.easeOut" style="z-index: 7; max-width: none; max-height: none; white-space: nowrap; min-height: 0px; min-width: 0px; line-height: 23px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 14px; left: 541.5px; top: 362.614px; visibility: visible; opacity: 0; transform: translate3d(0px, 0px, 0px);"><a href="http://joomlead.com/" class="ot-btn btn-main-color text-cap " style="min-height: 0px; min-width: 0px; line-height: 36px; border-width: 0px; margin: 0px 0px 13.5214px; padding: 0px 23px; letter-spacing: 0px; font-size: 11px;">Our Projects</a> &nbsp; <a href="http://joomlead.com/" class="ot-btn btn-sub-color text-cap " style="min-height: 0px; min-width: 0px; line-height: 36px; border-width: 0px; margin: 0px 0px 13.5214px; padding: 0px 23px; letter-spacing: 0px; font-size: 11px;">Get a Quote</a>
		</div>
	</li>
	<!-- SLIDE  2-->
	<li data-transition="fade" data-slotamount="1" data-masterspeed="1500" data-delay="13000" data-saveperformance="off" class="tp-revslider-slidesli active-revslide current-sr-slide-visible" style="width: 100%; height: 100%; overflow: hidden; visibility: inherit; opacity: 1; z-index: 20;">
		<!-- MAIN IMAGE -->
		<div class="slotholder" style="width:100%;height:100%;" data-duration="14000" data-zoomstart="undefined" data-zoomend="undefined" data-rotationstart="undefined" data-rotationend="undefined" data-ease="Linear.easeNone" data-bgpositionend="right center" data-bgposition="left center" data-kenburns="on" data-easeme="Linear.easeNone" data-bgfit="100" data-bgfitend="130" data-owidth="undefined" data-oheight="undefined"><div class="tp-bgimg defaultimg" data-lazyload="undefined" data-bgfit="100" data-bgposition="left center" data-bgrepeat="no-repeat" data-lazydone="undefined" src="http://demo.joomlead.com/arc/images/lead/slides/1.jpg" data-src="http://demo.joomlead.com/arc/images/lead/slides/1.jpg" style="background-color: rgba(0, 0, 0, 0); background-repeat: no-repeat; background-image: url(&quot;http://demo.joomlead.com/arc/images/lead/slides/1.jpg&quot;); background-position: 6.0279% 0%; width: 100%; height: 100%; opacity: 1; visibility: inherit; background-size: 125.527% 123.066%; transform: matrix(1, 0, 0, 1, 0, 0);"></div><div class="kenburnimg" style="position:absolute;z-index:1;width:100%;height:100%;top:0px;left:0px;"><img src="http://demo.joomlead.com/arc/images/lead/slides/1.jpg" style="-moz-user-select: none; position: absolute; width: 102%; height: 100%; left: 0px; top: 0px; visibility: inherit; opacity: 1; transform: translate3d(-3.95357px, 0px, 0px) scale(1.04393, 1.04393); transform-origin: 0% 0% 0px;"></div></div>
		<!-- LAYERS -->

		<!-- LAYER NR. 1 -->
		<div class="tp-caption large_text lft fadeout tp-resizeme start" data-x="center" data-hoffset="0" data-y="center" data-voffset="-140" data-speed="900" data-start="500" data-easing="Power4.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.15" data-endelementdelay="0.1" data-endspeed="1000" data-endeasing="Power1.easeOut" style="z-index: 5; max-width: none; max-height: none; white-space: nowrap; min-height: 0px; min-width: 0px; line-height: 36px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 4px; font-size: 27px; left: 527px; top: 171.3px; visibility: visible; opacity: 1; transform: translate3d(0px, 0px, 0px);">bedroom interior
		</div>

		<!-- LAYER NR. 2 -->
		<div class="tp-caption finewide_large_white lfb fadeout tp-resizeme start" data-x="center" data-hoffset="0" data-y="center" data-voffset="-40" data-speed="1200" data-start="500" data-easing="Power4.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.05" data-endelementdelay="0.1" data-endspeed="300" data-endeasing="Power1.easeOut" style="z-index: 6; max-width: none; max-height: none; white-space: nowrap; min-height: 0px; min-width: 0px; line-height: 54px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 2px; font-size: 65px; left: 386px; top: 252.443px; visibility: visible; opacity: 1; transform: translate3d(0px, 0px, 0px);">Design Awards
		</div>

		<!-- LAYER NR. 3 -->
		<div class="tp-caption sfr fadeout tp-resizeme start" data-x="center" data-hoffset="0" data-y="center" data-voffset="80" data-speed="1300" data-start="510" data-easing="Power4.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.15" data-endelementdelay="0.1" data-endspeed="300" data-endeasing="Power1.easeOut" style="z-index: 7; max-width: none; max-height: none; white-space: nowrap; min-height: 0px; min-width: 0px; line-height: 23px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 14px; left: 541.5px; top: 362.614px; visibility: visible; opacity: 1; transform: translate3d(0px, 0px, 0px);"><a href="http://joomlead.com/" class="ot-btn btn-main-color text-cap " style="min-height: 0px; min-width: 0px; line-height: 36px; border-width: 0px; margin: 0px 0px 13.5214px; padding: 0px 23px; letter-spacing: 0px; font-size: 11px;">Our Projects</a> &nbsp; <a href="http://joomlead.com/" class="ot-btn btn-sub-color text-cap " style="min-height: 0px; min-width: 0px; line-height: 36px; border-width: 0px; margin: 0px 0px 13.5214px; padding: 0px 23px; letter-spacing: 0px; font-size: 11px;">Get a Quote</a>
		</div>
	</li>
</ul>
	  <!---------------------->
	 
